name: Do a Duolingo lesson

on:
  workflow_dispatch:
    inputs:
      target_xp:
        default: 100
        description: 'Target XP for the number of lessons'
        required: false
        type: number

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          TARGET_XP: ${{ inputs.target_xp }}
